services:
  db:
    image: mariadb:latest
    container_name: mariadb # Buena práctica para identificar el contenedor fácilmente
    restart: always # Reinicia el contenedor si falla
    environment:
      MYSQL_DATABASE: orientacion
      MYSQL_ROOT_PASSWORD: root  # En desarrollo, está bien; en producción, usa secretos
      MYSQL_USER: user_orientacion # Crea un usuario específico para tu aplicación (mejor práctica)
      MYSQL_PASSWORD: password_orientacion # Contraseña para el usuario de la aplicación
    ports:
      - "3306:3306" # Mapea el puerto para acceder desde el host (opcional en producción)
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:mariadb://db:3306/orientacion # Usa 'db' como hostname
      DATABASE_USER: user_orientacion # Usa el usuario que creaste para la aplicación
      DATABASE_PASSWORD: password_orientacion
    # No necesitas mapear el puerto 3306 aquí. El backend se comunica con la BD dentro de la red Docker
    # volumes: # No es necesario volver a definir el volumen aquí.

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    # restart: always
    ports:
      - 5173:5173
    depends_on:
      - backend
      

volumes:
  mariadb_data:
    driver: local