# HTTP Server Port
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: student-attention
    version: 0.0.1-SNAPSHOT
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    # Database credentials
    url: jdbc:mariadb://db:3306/orientacion
    username: user_orientacion
    password: password_orientacion
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
